import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Explicit order, not the "autogenerated" type — this mirrors
// docs/core-service.md's own section order exactly (1. What Birr Is
// through 7. Summary, folded into 5 pages), so a reader moving through
// the sidebar top to bottom gets the same narrative arc that file has.
const sidebars: SidebarsConfig = {
  docsSidebar: ["intro", "waqf-funds", "vaults", "governance", "compliance"],
};

export default sidebars;
